let name = prompt();
const responseObj = {
    hello: "Hey! What's up, What's your name",
    ["Satyam"]: "Hello 'Satyam' how may I help you",
    ["satyam kumar mishra"]: "Hello 'Satyam' how may I help you",
    ["satyam kumar"]: "Hello 'Satyam' how may I help you",
    ["Chhatish"]: "Hello 'Chhatish' how may I help you",
    ["chhatish kumar"]: "Hello 'Chhatish' how may I help you",
    ["Chhoti"]: "Hello 'Chhoti' how may I help you",
    ["chhoti kumari"]: "Hello 'Chhoti' how may I help you",
    ["chhoti"]: "Hello 'Chhoti' how may I help you",
    ["Arpit"]: "Hello 'Arpit' how may I help you",
    ["arpit raj"]: "Hello 'Arpit' how may I help you",
    ["arpit"]: "Hello 'Satyam' how may I help you",
    ["Rohan"]: "Hello 'Rohan' how may I help you",
    ["rohan kumar"]: "Hello 'Rohan' how may I help you",
    ["rohan"]: "Hello 'Rohan' how may I help you",
    ["Aryan"]: "Hello 'Aryan' how may I help you",
    ["aryan kumar"]: "Hello 'Aryan' how may I help you",
    ["aryan"]: "Hello 'Aryan' how may I help you",
    ["aryan swarnakar"]: "Hello 'Aryan' how may I help you",
    ["Abhay"]: "Hello 'Abhay' how may I help you",
    ["abhay"]: "Hello 'Abhay' how may I help you",
    ["abhay kumar"]: "Hello 'abhay' how may I help you",
    ["Nitish"]: "Hello 'Nitish' how may I help you",
    ["nitish kumar"]: "Hello 'Nitish' how may I help you",
    ["nitish"]: "Hello 'Nitish' how may I help you",
    ["shiwansh"]: "Hello 'Shiwansh' how may I help you",
    ["Shiwansh kumar"]: "Hello 'Shiwansh' how may I help you",
    ["salman"]: "Hello 'Salman' how may I help you",
    ["Salman"]: "Hello 'Salman' how may I help you",
    ["Mayank"]: "Hello 'Mayank' how may I help you",
    ["mayank"]: "Hello 'Mayank' how may I help you",
    ["shravan"]: "Hello 'Shravan' how may I help you",
    ["unnati"]: "Hello 'Unnati' how may I help you",
    ["adhya"]: "Hello 'Adhya' how may I help you",
    ["nitin"]: "Hello 'Nitin' how may I help you",
    ["gaurav"]: "Hello 'Gaurav' how may I help you",
    ["aditya"]: "Hello 'Aditya' how may I help you",
    ["amit"]: "Hello 'Amit' how may I help you",
    ["praveen"]: "Hello 'Praveen' how may I help you",
    ["suresh"]: "Hello 'Suresh' how may I help you",
    ["purvi"]: "Hello 'Purvi' how may I help you",
    ["ankit"]: "Hello 'Ankit' how may I help you",
    ["hariom"]: "Hello 'Hariom' how may I help you",
    ["vivek"]: "Hello 'Vivek' how may I help you",
    ["kashif"]: "Hello 'Kashif' how may I help you",
    ["shawood"]: "Hello 'Shawood' how may I help you",
    ["keshav"]: "Hello 'Keshav' how may I help you",
    ["natwar"]: "Hello 'Natwar' how may I help you",
    ["suhani"]: "Hello 'Suhai' how may I help you",
    ["kishan"]: "Hello 'Kishan' how may I help you",
    ["neha"]: "Hello 'Neha' how may I help you",
    ["shikha"]: "Hello 'Shikha' how may I help you",
    ["roshni"]: "Hello 'Roshni' how may I help you",
    ["siwach"]: "Hello 'Siwach' how may I help you",
    ["shatmanyu"]: "Hello 'Satmanyu' how may I help you",

    hii: "Hello, What's you name ",
    Hii: "Hello, What's you name ",
    today: new Date().toDateString(),
    Today: new Date().toDateString(),
    Hello: "Hey What's up, Waht's your name ",
    time: new Date().toLocaleTimeString(),
    Time: new Date().toLocaleTimeString(),
    1: "Please type/copy 'niet.co.in' on your browser press 2 for Information about IOT",
    2: "Internet of things is to connect the one things to another things.",
    ["how are you"]: "I am fine, How may i help you?",
    ["what is your name"]:
        "My name is ChatBot a I work to provide info about Internet of Things and what is your name?",
    ["i want to know about NIET"]:
        "Please type/copy 'niet.co.in' on your chrome you will get more info",
    ["i want to know about niet"]:
        "Please type/copy 'niet.co.in' on your chrome you will get more info",
    ["i want to know about niet college"]:
        "Please type/copy 'niet.co.in' on your chrome you will get more info",
    ["I want to know about niet"]:
        "Please type/copy 'niet.co.in' on your chrome you will get more info",
    ["I want to know about NIET"]:
        "Please type/copy 'niet.co.in' on your chrome you will get more info",
    ["i want to know about internet of things"]:
        "Please type/copy 'https://en.wikipedia.org/wiki/Internet_of_things' in/paste your browser..",
    ["I want to know about IOT"]:
        "Please type/copy 'https://en.wikipedia.org/wiki/Internet_of_things' in/paste your browser..",
    ["give me info about iot"]:
        "Please type/copy 'https://en.wikipedia.org/wiki/Internet_of_things' in/paste your browser..",
    ["tell me about iot"]:
        "Please type/copy 'https://en.wikipedia.org/wiki/Internet_of_things' in/paste your browser..",
    ["what is iot"]:
        "Please type/copy 'https://en.wikipedia.org/wiki/Internet_of_things' in/paste your browser..",
};
